storage:
  classname: tsdat.io.FilesystemStorage
  parameters:
    retain_input_files: True
    root_dir: ${CONFIG_DIR}/../storage/root

  file_handlers:
    input:
      csv:
        file_pattern: '.*\.csv'
        classname: tsdat.io.handlers.CsvHandler

    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.handlers.NetCdfHandler
