storage:
  classname: tsdat.io.FilesystemStorage
  parameters:
    retain_input_files: True
    root_dir: ${CONFIG_DIR}/../storage/root

  file_handlers:
    input:
      zip:
        file_pattern: ['.*\.zip']
        classname: "tsdat.io.handlers.ZipHandler"
        parameters:
          handlers:
            csv:
              file_pattern: '.*\.csv'
              classname: tsdat.io.handlers.CsvHandler

    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.handlers.NetCdfHandler
