# Default environment for developing ADI Python apps

name: tsdat
channels:
  - arm-doe
  - conda-forge
dependencies:
  - python=3.9.15
  - libcds3
  - libtrans
  - libdsproc3
  - xarray>=0.20
  - numpy=1.23.1
  - pandas>=1.2
