# Default environment for developing ADI Python apps

name: tsdat
channels:
  - arm-doe
  - conda-forge
dependencies:
  - python=3.9
  - libcds3
  - libtrans
  - libdsproc3
  - pip=22.3.1
  - numpy=1.23.1
