site_name: tsdat
site_url: https://tsdat.readthedocs.io
site_description: Tsdat documentation.
site_author: Tsdat team

repo_url: https://github.com/tsdat/tsdat/
edit_uri: blob/main/docs/

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details  # makes notes collapsible
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

plugins: 
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # members_order: source
            docstring_section_style: list
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            show_source: true
            show_submodules: true
            filters:
              - "!^_"
              - "^__init__$"

# watch:
#   - tsdat
