site_name: tsdat
site_url: https://tsdat.readthedocs.io
site_description: Tsdat documentation.
site_author: Tsdat team
repo_url: https://github.com/tsdat/tsdat/
edit_uri: blob/main/docs/

extra: 
  analytics:
    provider: google
    property: G-02LXGHFVQG

nav:
  - About: index.md
  - Getting Started: getting_started.md
  - Tutorials: tutorials/
  - Developer Guide:
      - Customizing Tsdat: config/configuring_tsdat.md
      - Dataset Config: config/dataset_config.md
      - Retriever Config: config/retriever_config.md
      - Quality Config: config/quality_control.md
      - Storage Config: config/storage_config.md
      - Pipeline Config: config/pipeline_config.md
      - Pipeline Code Hooks: config/hook_functions.md
      - Transformation Pipelines: config/transform_config.md
      - Pydantic and Parameters: config/pydantic.md
  - API Reference: API/
  - Contributing: collaboration.md

theme:
  name: material
  logo: figures/tsdat_logo.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    - toc.integrate
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details  # makes notes collapsible
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

plugins: 
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      implicit_index: false
      tab_length: 4
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # https://mkdocstrings.github.io/python/usage/#configuration
            docstring_section_style: table
            heading_level: 2
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            show_source: true
            show_submodules: true
            summary: true
            show_if_no_docstring: true
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: true
            show_category_heading: true
            filters:
              # Exclude certain lines from being included in the API docs
              - "!^_"
              - "!^logger"
              - "!^ureg"
              # - "^__init__$"

# watch:
#   - tsdat
