pipeline:
  type: Ingest

  location_id: "humboldt"
  dataset_name: "buoy_z05"
  qualifier: "imu"
  # temporal:
  data_level: "a1"

dataset_definition:
  attributes:
    title: "IMU Buoy Dataset"
    description: "Euler angles, accelerometer, magnetometer and Gyroscope data"
    doi: 10.21947/1671051
    conventions: "ME Data Pipeline Standards: Version 1.0"
    institution: Pacific Northwest National Laboratory
    code_url: https://github.com/tsdat/tsdat/releases/tag/v0.2.2
    location_meaning: Humboldt, CA
    instrument_name: GX5-45 IMU
    instrument_meaning: Self-powered floating buoy hosting a suite of meteorological and marine instruments.
    instrument_manufacturer: AXYS Technologies Inc.

  dimensions:
    time:
      length: unlimited
    space:
      length: 3    

  variables:

    time:
      input:
        name: time
      dims: [time]
      type: long
      attrs:
        long_name: Time offset from epoch
        standard_name: time
        units: microseconds since 1980-01-06T00:00:00

    space:
      input:
        name: space
      dims: [space]
      type: str
      attrs:
        long_name: Spatial Components
        units: "1"

    roll:  
      input: 
        name: roll
        units: radians
      dims: [time]
      type: double
      attrs:
        long_name: Roll
        definition: "The roll angle measures the side to side motion of the 
        buoy between the starboard and port side. The roll angle is measured 
        in degrees around the longitudinal axis of buoy that runs fore and 
        aft. A roll angle of 0ยบ means that the buoy is flat with respect to 
        the earth in the side to side direction. Buoy rotation towards the 
        starboard (right) side is a positive roll angle."
        instrument: "MicroStrain, 3DM GX3 25 (Instrument # NA)"
        units: degrees

    pitch:  
      input: 
        name: pitch
        units: radians
      dims: [time]
      type: double
      attrs:
        long_name: Pitch
        definition: "The pitch angle measures the front to back motion of the 
        buoy fore and aft. The pitch angle is measured in degrees around the 
        lateral axis of buoy that runs from port to starboard. A pitch angle 
        of 0ยบ means that the buoy is flat with respect to the earth in the 
        fore to aft direction. Buoy rotation towards the fore (front) is a 
        positive pitch angle."
        instrument: "MicroStrain, 3DM GX3 25 (Instrument # NA)"
        units: degrees

    yaw:  
      input: 
        name: yaw
        units: radians
      dims: [time]
      type: double
      attrs:
        long_name: Yaw
        units: degrees

    gyro:  
      input: 
        name: gyro
        units: radians
      dims: [time, space]
      type: double
      attrs:
        long_name: Gyrometer
        units: degrees

    accel:  
      input: 
        name: accel
      dims: [time, space]
      type: double
      attrs:
        long_name: Acceleration
        units: m/s^2

    mag:  
      input: 
        name: mag
      dims: [time, space]
      type: double
      attrs:
        long_name: Magnetic field strength 
        units: gauss
    
    pres:  
      input: 
        name: pres
      dims: [time]
      type: double
      attrs:
        long_name: Pressure
        units: hPa
    

#-----------------------------------------------------------------
quality_management:

  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - time

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - time
  
  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
