readers:
  # classname: tsdat.io.readers.ReaderController??
  csv:
    regex: .*\.csv
    classname: tsdat.io.readers.CsvReader
    parameters:
      header: 22

  parquet:
    regex: .*\.parquet
    classname: tsdat.io.readers.ParquetReader

storage:
  classname: tsdat.io.storage.FileSystem
  parameters: {}

  writers:
    netcdf:
      classname: tsdat.io.storage.writers.NetCDFWriter
