# The storage configuration file is now solely responsible saving data and ancillary
# files. All data retrieval operations (except, possible, read operations on previously-
# saved data) now take place using a Retriver class and customization is done in the
# retriever-config.yaml file.
classname: tsdat.io.storage.FileSystem
parameters: {}

writers:
  netcdf:
    classname: tsdat.io.handlers.NetCDFWriter
    parameters: {}
