# just renamed to config.yaml to prevent validation during ideation phase.
# pipeline.yaml

classname: tsdat.pipeline.ingest.IngestPipeline

associations:
  - '.*\.csv'

retriever:
  path: ideas/simple/retriever.yaml

io:
  path: ideas/simple/io.yaml

dataset:
  path: ideas/simple/dataset.yaml

quality:
  path: ideas/simple/qc.yaml
