# just renamed to config.yaml to prevent validation during ideation phase.
# pipeline.yaml

classname: tsdat.pipeline.ingest.IngestPipeline

associations:
  - .*\.csv

retriever:
  path: ideas/simple/retriever.yaml

dataset:
  path: ideas/simple/dataset.yaml

quality:
  path: ideas/simple/qc.yaml

storage:
  path: ideas/simple/io.yaml
